### ISSUE TITLE
Enabling the addon & registering it leads to NextCloud 504 Error

### ISSUE THREAD

**Issue by LokeYourC3PH** [aaochat/aaochat#2]
Hello there AAOChat team, I'd like to quickly explain my issue and provide you with an error log as well.
So, once I enabled AAOChat and registered it with the given code from my Email, NextCloud stopped functioning immediately, leading to a 504 Error. I could solve this only by diabling AAOChat via OCC over SSH.

The following error(s) appeared in the log:

```
[PHP] Error: Error: Undefined variable $ZM at /home/*redacted*/web/cloud.*redacted*/public_html/apps/aaochat/templates/settings/admin-form.php#89 at <<closure>>

 0. /home/*redacted*/web/cloud.*redacted*/public_html/apps/aaochat/templates/settings/admin-form.php line 89
    OC\Log\ErrorHandler::onError(2, "Undefined variable $ZM", "/home/*redacted*/ ... p", 89)
 1. /home/*redacted*/web/cloud.*redacted*/public_html/lib/private/Template/Base.php line 180
    include("/home/*redacted*/ ... p")
 2. /home/*redacted*/web/cloud.*redacted*/public_html/lib/private/Template/Base.php line 150
    OC\Template\Base->load("/home/*redacted*/ ... p", ["64113e0aee248d ... "])
 3. /home/*redacted*/web/cloud.*redacted*/public_html/lib/private/legacy/OC_Template.php line 181
    OC\Template\Base->fetchPage(["64113e0aee248d ... "])
 4. /home/*redacted*/web/cloud.*redacted*/public_html/lib/public/AppFramework/Http/TemplateResponse.php line 213
    OC_Template->fetchPage(["64113e0aee248d ... "])
 5. /home/*redacted*/web/cloud.*redacted*/public_html/apps/settings/lib/Controller/CommonSettingsTrait.php line 130
    OCP\AppFramework\Http\TemplateResponse->render()
 6. /home/*redacted*/web/cloud.*redacted*/public_html/apps/settings/lib/Controller/AdminSettingsController.php line 83
    OCA\Settings\Controller\AdminSettingsController->formatSettings([[["OCA\\AaoChat ... ]])
 7. /home/*redacted*/web/cloud.*redacted*/public_html/apps/settings/lib/Controller/CommonSettingsTrait.php line 149
    OCA\Settings\Controller\AdminSettingsController->getSettings("aaochat")
 8. /home/*redacted*/web/cloud.*redacted*/public_html/apps/settings/lib/Controller/AdminSettingsController.php line 68
    OCA\Settings\Controller\AdminSettingsController->getIndexResponse("admin", "aaochat")
 9. /home/*redacted*/web/cloud.*redacted*/public_html/lib/private/AppFramework/Http/Dispatcher.php line 225
    OCA\Settings\Controller\AdminSettingsController->index("aaochat")
10. /home/*redacted*/web/cloud.*redacted*/public_html/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController(["OCA\\Settings\ ... "], "index")
11. /home/*redacted*/web/cloud.*redacted*/public_html/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch(["OCA\\Settings\ ... "], "index")
12. /home/*redacted*/web/cloud.*redacted*/public_html/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main("OCA\\Settings\\ ... r", "index", ["OC\\AppFramewo ... "], ["aaochat","sett ... "])
13. /home/*redacted*/web/cloud.*redacted*/public_html/lib/base.php line 1047
    OC\Route\Router->match("/settings/admin/aaochat")
14. /home/*redacted*/web/cloud.*redacted*/public_html/index.php line 36
    OC::handleRequest()

GET /settings/admin/aaochat
from xxx.xxx.xxx.xxx by *redacted* at 2023-03-16T16:05:06+00:00
```

There were many of the same ones, just with different values after the "Undefined variable $" in the first line, which looks like this:
![image](https://user-images.githubusercontent.com/5807595/225892098-1d86b12e-2f83-4374-a01b-43b8f98f232a.png)

Hope you're able to do something about it :)

**Comment by parth2326** [comment]
@LokeYourLord can you please me know which nextcloud version are you using?

**Comment by LokeYourC3PH** [comment]
Oh sorry, 25.0.4 latest on Ubuntu 22.04 server that runs on ARMx64 architecture.

**Comment by parth2326** [comment]
@LokeYourLord Please update the plugin. Version 0.0.3 (latest) should fix this issue.

**Comment by LokeYourC3PH** [comment]
0.0.3 is already the latest version, I think that you should set the newest NextCloud version to 0.0.4, because it does not show me that there is an update available.

**Comment by LokeYourC3PH** [comment]
Alright, after updating, the issue persists, however no logs this time, so not sure what else I can do now to provide you with any logs.

**Comment by parth2326** [comment]
@LokeYourLord if possible we would like to look into the issue on your system. if possible do send me your email address on aaochat007@gmail.com and we can setup a meeting to look into it. Thank you.
